/** @format */
import Head from "next/head";
import Frame from "../components/layout/Frame";
import Concept from "../components/Concept";
import CompanyStats from "../components/CompanyStats";
import AboutInfo from "../components/AboutInfo";
const About = () => {
  return (
    <Frame>
      <Head>
        <title>Halal Ride | About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <AboutInfo />
        <CompanyStats />
        <Concept />
      </main>
    </Frame>
  );
};

export default About;
