/** @format */

import Head from "next/head";
import ContactUs from "../components/ContactUs";
import Frame from "../components/layout/Frame";
import Location from "../components/Location";

const Contact = () => {
  return (
    <>
      <Head>
        <title>Halal Ride | Contact</title>
        <meta
          name='description'
          content='Generated byHabibu with  create next app'
        />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <Frame>
        <main className='main'>
          <ContactUs />
          <Location />
        </main>
      </Frame>
    </>
  );
};

export default Contact;
