/** @format */

import Head from "next/head";
import ContactUs from "../components/ContactUs";
import Frame from "../components/layout/Frame";
import Location from "../components/Location";

const Contact = () => {
  return (
    <Frame>
      <Head>
        <title>Halal Ride | Contact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='main'>
        <ContactUs />
        <Location />
      </main>
    </Frame>
  );
};

export default Contact;
